# Generated by Django 4.2.3 on 2023-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
